site_name: ChemistryEdu
site_url: https://chemistryedu.org
copyright: Copyright © chemistryedu.org 2023

markdown_extensions:
  - toc:
      permalink: "#"
      toc_depth: 2
  - admonition
  - codehilite
  - def_list
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
  - pymdownx.details
  - pymdownx.snippets:
      check_paths: true
  - pymdownx.superfences
  - pymdownx.tabbed
  - sane_lists
  - attr_list
  - md_in_html
  - pymdownx.arithmatex:
      generic: true


extra:
  generator: false
# TODO: Uncomment analytics later
#  analytics:
#    provider: google
#    property: G-XYZX98MFG8
  consent:
    title: Cookie consent
    description: >-
      We use cookies to recognize your repeated visits and preferences, as well
      as to measure the effectiveness of our documentation and whether users
      find what they're searching for. With your consent, you're helping us to
      make our documentation better.

extra_css:
  - stylesheets/extra.css

extra_javascript:
  - javascripts/mathjax.js
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js

plugins:
  - glightbox
  - search

theme:
  name: material
  language: en
  favicon: images/favicon.svg
  logo: images/favicon.svg
  palette:
    primary: teal
    accent: teal
  features:
    - search.suggest
    - navigation.indexes

nav:
  - Home: index.md
  - Physical Chemistry:
      - physical-chemistry/index.md
      - Mole Concept:
          - Introduction: physical-chemistry/mole-concept/introduction.md
          - Calculation of Moles: physical-chemistry/mole-concept/calculation-of-moles.md
          - Calculation of Moles for an ideal gas: physical-chemistry/mole-concept/calculation-of-moles-for-gases.md
  - Policies:
    - Terms and Conditions: policies/terms-and-conditions.md
    - Disclaimer: policies/disclaimer.md
    - Privacy Policy: policies/privacy-policy.md
  - Contact Us: contact-us/index.md