site_name: ChemistryEdu
site_url: https://chemistryedu.org
copyright: Copyright &copy; chemistryedu.org 2024

markdown_extensions:
  - toc:
      permalink: "#"
      toc_depth: 2
  - admonition
  - tables
  - codehilite
  - def_list
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
  - pymdownx.details
  - pymdownx.snippets:
      check_paths: true
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true
  - sane_lists
  - attr_list
  - md_in_html
  - pymdownx.arithmatex:
      generic: true

extra:
  generator: false

extra_css:
  - stylesheets/extra.css

extra_javascript:
  - javascripts/mathjax.js
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js
  - https://pagead2.googlesyndication.com/pagead/js/adsbygoogle.js?client=ca-pub-2873642389965415
  - https://www.googletagmanager.com/gtag/js?id=G-XYZX98MFG8
  - javascripts/extra.js

plugins:
  - glightbox
  - search
  - minify:
      minify_html: true
      minify_js: true
      minify_css: true
      htmlmin_opts:
        remove_comments: true
      js_files:
        - javascripts/mathjax.js
        - javascripts/extra.js
      css_files:
        - stylesheets/extra.css

theme:
  name: material
  language: en
  favicon: images/favicon.svg
  logo: images/favicon.svg
  palette:
  # Palette toggle for automatic mode
    - media: "(prefers-color-scheme)"
      scheme: default
      toggle:
        icon: material/brightness-auto
        name: Switch to dark mode
      primary: teal
      accent: teal

  # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      toggle:
        icon: material/brightness-7
        name: Switch to system preference
      primary: teal
      accent: teal

  # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
      primary: teal
      accent: teal

  features:
    - navigation.prune
    - navigation.tabs
    - navigation.top
    - navigation.tabs.sticky
    - navigation.tracking
    - navigation.footer
    - toc.follow
    - search.highlight
    - search.suggest

nav:
  - Home: index.md
  - Physical Chemistry:
      - Mole Concept:
          - Introduction: physical-chemistry/mole-concept/introduction.md
          - Calculation of Moles: physical-chemistry/mole-concept/calculation-of-moles.md
          - Calculation of Moles for an ideal gas: physical-chemistry/mole-concept/calculation-of-moles-for-gases.md
          - Limiting Reagent: physical-chemistry/mole-concept/limiting-reagent.md
          - Vapour Density: physical-chemistry/mole-concept/vapour-density.md
          - Empirical and Molecular Formula: physical-chemistry/mole-concept/empirical-and-molecular-formula.md
          - Concentration Terms: physical-chemistry/mole-concept/concentration-terms.md
      - Gaseous State:
          - Introduction: physical-chemistry/gaseous-state/introduction.md
          - Gas Laws: physical-chemistry/gaseous-state/gas-laws.md
          - Ideal Gas Equation: physical-chemistry/gaseous-state/ideal-gas-equation.md
          - Kinetic Theory of Gases: physical-chemistry/gaseous-state/kinetic-theory-of-gases.md
      - Thermodynamics:
          - Introduction: physical-chemistry/thermodynamics/introduction.md
          - Thermodynamic Processes: physical-chemistry/thermodynamics/thermodynamic-processes.md
          - Heat, Work and Internal energy: physical-chemistry/thermodynamics/heat-work-and-internal-energy.md
          - First Law of Thermodynamics: physical-chemistry/thermodynamics/first-law-of-thermodynamics.md
          - Enthalpy: physical-chemistry/thermodynamics/enthalpy.md
          - Heat Capacity: physical-chemistry/thermodynamics/heat-capacity.md
          - Degree of Freedom: physical-chemistry/thermodynamics/degree-of-freedom.md
          - Reversible and Irreversible Processes: physical-chemistry/thermodynamics/reversible-and-irreversible-processes.md
          - Analysis of Thermodynamic Processes: physical-chemistry/thermodynamics/analysis-of-thermodynamic-processes.md
          - Questions based on Work done: physical-chemistry/thermodynamics/questions-based-on-work-done.md
          - Questions based on First Law of Thermodynamics: physical-chemistry/thermodynamics/questions-based-on-first-law-of-thermodynamics.md
          - Graph Based Questions: physical-chemistry/thermodynamics/graph-based-questions.md
          - Polytropic Process: physical-chemistry/thermodynamics/polytropic-process.md
          - Spontaneous and Non-Spontaneous Processes: physical-chemistry/thermodynamics/spontaneous-and-non-spontaneous-processes.md
          - Entropy: physical-chemistry/thermodynamics/entropy.md
          - Questions based on Entropy: physical-chemistry/thermodynamics/questions-based-on-entropy.md
          - Carnot Cycle and Second Law of Thermodynamics: physical-chemistry/thermodynamics/carnot-cycle-and-second-law-of-thermodynamics.md
          - Gibbs Free Energy and Third Law of Thermodynamics: physical-chemistry/thermodynamics/gibbs-free-energy-and-third-law-of-thermodynamics.md
      - Chemical Equilibrium:
          - Introduction: physical-chemistry/chemical-equilibrium/introduction.md
          - Law of Mass Action: physical-chemistry/chemical-equilibrium/law-of-mass-action.md
          - Equilibrium Constant: physical-chemistry/chemical-equilibrium/equilibrium-constant.md
          - Degree of Dissociation: physical-chemistry/chemical-equilibrium/degree-of-dissociation.md
          - Reaction Quotient: physical-chemistry/chemical-equilibrium/reaction-quotient.md
          - Le Chatelier's Principle: physical-chemistry/chemical-equilibrium/le-chateliers-principle.md
      - Solution:
          - Introduction: physical-chemistry/solution/introduction.md
          - Concentration Terms: physical-chemistry/solution/concentration-terms.md
          - Questions based on Concentration Terms: physical-chemistry/solution/questions-based-on-concentration-terms.md
          - Solubility of Solid in Liquid: physical-chemistry/solution/solubility-of-solid-in-liquid.md
          - Solubility of Gas in Liquid: physical-chemistry/solution/solubility-of-gas-in-liquid.md
          - Vapour Pressure of Liquid Solution: physical-chemistry/solution/vapour-pressure-of-liquid-solution.md
          - Raoult's Law: physical-chemistry/solution/raoult's-law.md
          - Ideal and Non-Ideal Solutions: physical-chemistry/solution/ideal-and-non-ideal-solutions.md
          - Azeotropes and Zeotropes: physical-chemistry/solution/azeotropes-and-zeotropes.md
          - Solution of Solids in Liquid: physical-chemistry/solution/solution-of-solids-in-liquids.md
          - Colligative Properties of Dilute Solution: physical-chemistry/solution/colligative-properties-of-dilute-solutions.md
      - Electrochemistry:
          - Introduction: physical-chemistry/electrochemistry/introduction.md
          - Faraday's Laws of Electrolysis: physical-chemistry/electrochemistry/faraday's-laws-of-electrolysis.md
          - Electrochemical Cells: physical-chemistry/electrochemistry/electrochemical-cells.md
          - Electrode Potential: physical-chemistry/electrochemistry/electrode-potential.md
          - EMF of a Cell: physical-chemistry/electrochemistry/emf-of-a-cell.md
          - Nernst Equation: physical-chemistry/electrochemistry/nernst-equation.md
          - Questions Based on Nernst Equation: physical-chemistry/electrochemistry/questions-based-on-nernst-equation.md
          - Conductance of Electrolytic Solutions: physical-chemistry/electrochemistry/conductance-of-electrolytic-solutions.md
          - Variation of Conductivity and Molar Conductivity with Concentration: physical-chemistry/electrochemistry/variation-of-conductivity-with-concentration.md
          - Questions based on Conductivity: physical-chemistry/electrochemistry/questions-based-on-conductivity.md
          - Batteries and Corrosion: physical-chemistry/electrochemistry/batteries-and-corrosion.md
  - Inorganic Chemistry:
      - Periodicity:
          - Periodic Classification: inorganic-chemistry/periodicity/periodic-classification.md
          - Electronic configuration of atoms and Periodic Table: inorganic-chemistry/periodicity/electronic-configuration-and-periodic-table.md
          - Types of Elements: inorganic-chemistry/periodicity/types-of-elements.md
          - Metals, Non-Metals and Metalloids: inorganic-chemistry/periodicity/metals-non-metals-and-metalloids.md
          - Trends in Physical Properties: inorganic-chemistry/periodicity/trends-in-physical-properties.md
          - Trends in Chemical Properties: inorganic-chemistry/periodicity/trends-in-chemical-properties.md
      - s-block Elements:
          - Alkali Metals:
              - General Characteristics: inorganic-chemistry/s-block-elements/alkali-metals/general-characteristics.md
              - Physical Characteristics: inorganic-chemistry/s-block-elements/alkali-metals/physical-characteristics.md
              - Chemical Characteristics: inorganic-chemistry/s-block-elements/alkali-metals/chemical-characteristics.md
              - Compounds of Alkali Metals: inorganic-chemistry/s-block-elements/alkali-metals/compounds-of-alkali-metals.md
              - Anomalous Properties of Lithium: inorganic-chemistry/s-block-elements/alkali-metals/anomolous-properties-of-lithium.md
              - Compounds of Sodium: inorganic-chemistry/s-block-elements/alkali-metals/compounds-of-sodium.md
      - p-block Elements:
          - Group 16:
            - Atomic Properties: inorganic-chemistry/p-block-elements/group-16/atomic-properties.md
            - Physical Properties and Oxidation States: inorganic-chemistry/p-block-elements/group-16/physical-properties-and-oxidation-states.md
            - Chemical Reactivity: inorganic-chemistry/p-block-elements/group-16/chemical-reactivity.md
          - Group 17:
              - Physical and Atomic Properties: inorganic-chemistry/p-block-elements/group-17/physical-and-atomic-properties.md
              - Chemical Properties: inorganic-chemistry/p-block-elements/group-17/chemical-properties.md
              - Oxoacids and Interhalogen Compounds: inorganic-chemistry/p-block-elements/group-17/oxoacids-and-interhalogen-compounds.md
              - Important Compounds - Chlorine and HCl: inorganic-chemistry/p-block-elements/group-17/important-compounds-chlorine-and-hydrogen-chloride.md
          - Group 18:
              - Physical and Atomic Properties: inorganic-chemistry/p-block-elements/group-18/physical-and-atomic-properties.md
              - Chemical Properties: inorganic-chemistry/p-block-elements/group-18/chemical-properties.md
      - d- and f-block Elements:
          - d-block Elements:
              - Transition Elements: inorganic-chemistry/d-and-f-block-elements/d-block/transition-elements.md
              - Atomic and Ionic Sizes: inorganic-chemistry/d-and-f-block-elements/d-block/atomic-and-ionic-sizes.md
              - Ionization Enthalpy: inorganic-chemistry/d-and-f-block-elements/d-block/ionization-enthalpy.md
              - Oxidation States: inorganic-chemistry/d-and-f-block-elements/d-block/oxidation-states.md
              - Magnetic, Catalytic and Other Properties: inorganic-chemistry/d-and-f-block-elements/d-block/magnetic-catalytic-and-other-properties.md
          - f-block Elements:
              - Lanthanoids and their Properties: inorganic-chemistry/d-and-f-block-elements/f-block/lanthanoids-and-their-properties.md
              - Actinoids and their Properties: inorganic-chemistry/d-and-f-block-elements/f-block/actinoids-and-their-properties.md
  - Organic Chemistry:
      - Alkyl Halides:
          - Introduction: organic-chemistry/alkyl-halides/introduction-and-nomenclature.md
  - Policies:
      - Terms and Conditions: policies/terms-and-conditions.md
      - Disclaimer: policies/disclaimer.md
      - Privacy Policy: policies/privacy-policy.md
  - Contact Us: contact-us/index.md
