site_name: ChemistryEdu
site_url: https://chemistryedu.org
copyright: Copyright © chemistryedu.org 2023

markdown_extensions:
  - toc:
      permalink: "#"
      toc_depth: 2
  - admonition
  - tables
  - codehilite
  - def_list
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
  - pymdownx.details
  - pymdownx.snippets:
      check_paths: true
  - pymdownx.superfences
  - pymdownx.tabbed
  - sane_lists
  - attr_list
  - md_in_html
  - pymdownx.arithmatex:
      generic: true


extra:
  generator: false
# TODO: Uncomment analytics later
#  analytics:
#    provider: google
#    property: G-XYZX98MFG8
  consent:
    title: Cookie consent
    description: >-
      We use cookies to recognize your repeated visits and preferences, as well
      as to measure the effectiveness of our documentation and whether users
      find what they're searching for. With your consent, you're helping us to
      make our documentation better.

extra_css:
  - stylesheets/extra.css

extra_javascript:
  - javascripts/mathjax.js
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js

plugins:
  - glightbox
  - search

theme:
  name: material
  language: en
  favicon: images/favicon.svg
  logo: images/favicon.svg
  palette:
  # Palette toggle for automatic mode
    - media: "(prefers-color-scheme)"
      scheme: default
      toggle:
        icon: material/brightness-auto
        name: Switch to dark mode
      primary: teal
      accent: teal

  # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      toggle:
        icon: material/brightness-7
        name: Switch to system preference
      primary: teal
      accent: teal

  # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
      primary: teal
      accent: teal

  features:
    - search.suggest
    - navigation.indexes

nav:
  - Home: index.md
  - Physical Chemistry:
      - physical-chemistry/index.md
      - Mole Concept:
          - Introduction: physical-chemistry/mole-concept/introduction.md
          - Calculation of Moles: physical-chemistry/mole-concept/calculation-of-moles.md
          - Calculation of Moles for an ideal gas: physical-chemistry/mole-concept/calculation-of-moles-for-gases.md
          - Limiting Reagent: physical-chemistry/mole-concept/limiting-reagent.md
          - Vapour Density: physical-chemistry/mole-concept/vapour-density.md
          - Empirical and Molecular Formula: physical-chemistry/mole-concept/empirical-and-molecular-formula.md
          - Concentration Terms: physical-chemistry/mole-concept/concentration-terms.md
      - Thermodynamics:
          - Introduction: physical-chemistry/thermodynamics/introduction.md
          - Thermodynamic Processes: physical-chemistry/thermodynamics/thermodynamic-processes.md
          - Heat, Work and Internal energy: physical-chemistry/thermodynamics/heat-work-and-internal-energy.md
          - First Law of Thermodynamics: physical-chemistry/thermodynamics/first-law-of-thermodynamics.md
          - Enthalpy: physical-chemistry/thermodynamics/enthalpy.md
          - Heat Capacity: physical-chemistry/thermodynamics/heat-capacity.md
          - Degree of Freedom: physical-chemistry/thermodynamics/degree-of-freedom.md
          - Reversible and Irreversible Processes: physical-chemistry/thermodynamics/reversible-and-irreversible-processes.md
          - Analysis of Thermodynamic Processes: physical-chemistry/thermodynamics/analysis-of-thermodynamic-processes.md
          - Questions based on Work done: physical-chemistry/thermodynamics/questions-based-on-work-done.md
          - Questions based on First Law of Thermodynamics: physical-chemistry/thermodynamics/questions-based-on-first-law-of-thermodynamics.md
          - Graph Based Questions: physical-chemistry/thermodynamics/graph-based-questions.md
          - Polytropic Process: physical-chemistry/thermodynamics/polytropic-process.md
          - Spontaneous and Non-Spontaneous Processes: physical-chemistry/thermodynamics/spontaneous-and-non-spontaneous-processes.md
          - Entropy: physical-chemistry/thermodynamics/entropy.md
          - Questions based on Entropy: physical-chemistry/thermodynamics/questions-based-on-entropy.md
          - Carnot Cycle and Second Law of Thermodynamics: physical-chemistry/thermodynamics/carnot-cycle-and-second-law-of-thermodynamics.md
          - Gibbs Free Energy and Third Law of Thermodynamics: physical-chemistry/thermodynamics/gibbs-free-energy-and-third-law-of-thermodynamics.md
      - Chemical Equilibrium:
          - Introduction: physical-chemistry/chemical-equilibrium/introduction.md
          - Law of Mass Action: physical-chemistry/chemical-equilibrium/law-of-mass-action.md
          - Equilibrium Constant: physical-chemistry/chemical-equilibrium/equilibrium-constant.md
          - Degree of Dissociation: physical-chemistry/chemical-equilibrium/degree-of-dissociation.md
          - Reaction Quotient: physical-chemistry/chemical-equilibrium/reaction-quotient.md
          - Le Chatelier's Principle: physical-chemistry/chemical-equilibrium/le-chateliers-principle.md
      - Solution:
          - Introduction: physical-chemistry/solution/introduction.md
          - Concentration Terms: physical-chemistry/solution/concentration-terms.md
          - Questions based on Concentration Terms: physical-chemistry/solution/questions-based-on-concentration-terms.md
          - Solubility of Solid in Liquid: physical-chemistry/solution/solubility-of-solid-in-liquid.md
          - Solubility of Gas in Liquid: physical-chemistry/solution/solubility-of-gas-in-liquid.md
          - Vapour Pressure of Liquid Solution: physical-chemistry/solution/vapour-pressure-of-liquid-solution.md
          - Raoult's Law: physical-chemistry/solution/raoult's-law.md
          - Ideal and Non-Ideal Solutions: physical-chemistry/solution/ideal-and-non-ideal-solutions.md
          - Azeotropes and Zeotropes: physical-chemistry/solution/azeotropes-and-zeotropes.md
          - Solution of Solids in Liquid: physical-chemistry/solution/solution-of-solids-in-liquids.md
          - Colligative Properties of Dilute Solution: physical-chemistry/solution/colligative-properties-of-dilute-solutions.md
  - Inorganic Chemistry:
      - Periodicity:
          - Periodic Classification: inorganic-chemistry/periodicity/periodic-classification.md
          - Electronic configuration of atoms and Periodic Table: inorganic-chemistry/periodicity/electronic-configuration-and-periodic-table.md
          - Types of Elements: inorganic-chemistry/periodicity/types-of-elements.md
          - Metals, Non-Metals and Metalloids: inorganic-chemistry/periodicity/metals-non-metals-and-metalloids.md
          - Trends in Physical Properties: inorganic-chemistry/periodicity/trends-in-physical-properties.md
          - Trends in Chemical Properties: inorganic-chemistry/periodicity/trends-in-chemical-properties.md
      - p-block Elements:
          - Group 17:
              - Physical and Atomic Properties: inorganic-chemistry/p-block-elements/group-17/physical-and-atomic-properties.md
              - Chemical Properties: inorganic-chemistry/p-block-elements/group-17/chemical-properties.md
              - Oxoacids and Interhalogen Compounds: inorganic-chemistry/p-block-elements/group-17/oxoacids-and-interhalogen-compounds.md
              - Important Compounds - Chlorine and HCl: inorganic-chemistry/p-block-elements/group-17/important-compounds-chlorine-and-hydrogen-chloride.md
          - Group 18:
              - Physical and Atomic Properties: inorganic-chemistry/p-block-elements/group-18/physical-and-atomic-properties.md
              - Chemical Properties: inorganic-chemistry/p-block-elements/group-18/chemical-properties.md
  - Policies:
      - Terms and Conditions: policies/terms-and-conditions.md
      - Disclaimer: policies/disclaimer.md
      - Privacy Policy: policies/privacy-policy.md
  - Contact Us: contact-us/index.md
